apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ggirigirig/k8s-demo:latest
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: database-creds

          - name: SERVICE_DISCOVERY_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: database-creds

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 3000
