apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
# pass and username was be based64 encoded use <echo -n passworf123 | base64>
# to generate a base64 password and username
  mongo-user: bW9uZ291c2Vy
  mongo-password: cGFzc3dvcmQxMjM=