apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
  #this is how the service and pod will find each other (ln: 15)
    app: mongo
  ports:
    - protocol: TCP
      port: 3000
      # target port should always be the same and the container port (ln: 21)
      targetPort: 3000